name: Vercel Development Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  SERVER_DOCS_EXPOSE: ${{ vars.SERVER_DOCS_EXPOSE }}
on:
  push:
    branches:
      - develop
jobs:
  vercel_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c√≥digo fuente
        uses: actions/checkout@v2
      - name: Reemplazo
        uses: 73h/gae-app-yaml-replace-env-variables@v0.3
        env:
          SECRET_ONE: ${{ secrets.GCP_SEC }}
          SERVER_DOCS_EXPOSE:  ${{ env.SERVER_DOCS_EXPOSE }}
        with:
          app_yaml_path: "app.template.yaml"
      - name: Variables
        run: npx gae-ayaml-env

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{  env.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{  env.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{  env.VERCEL_TOKEN }}
